name: Publish To NuGet.org

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  unit-test:
    name: UnitTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore /p:ContinuousIntegrationBuild=true
      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage"
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: XuPeiYao/EdwardHsu.ModifyDetector
  publish:
    name: Build Package And Publish to NuGet.org
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore packages
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release /p:Version=${VERSION} --no-restore
        working-directory: EdwardHsu.ModifyDetector
      - name: Pack
        run: dotnet pack --configuration Release /p:Version=${VERSION} /p:IncludeSymbols=true /p:SymbolPackageFormat=snupkg --no-build --output .
        working-directory: EdwardHsu.ModifyDetector
      - name: Publish package to NuGet.org
        run: dotnet nuget push EdwardHsu.ModifyDetector.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        working-directory: EdwardHsu.ModifyDetector
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: Publish symbol-packages to NuGet.org
        run: dotnet nuget push EdwardHsu.ModifyDetector.${VERSION}.snupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_TOKEN}
        working-directory: EdwardHsu.ModifyDetector
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}