name: Unit Test

on:
  push:
  workflow_dispatch:

jobs:
  unit-test:
    name: UnitTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.x
      - name: Restore packages
        run: dotnet restore
      - name: Build
        run: dotnet build      
      - name: Unit Test
        run: dotnet test --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: XuPeiYao/EdwardHsu.ModifyDetector
      